Algoritmo "para...faca"

//  
// Descrição   : Material do Curso de Algoritmos do
//  canal Informaticode: www.informaticode.com.br
// Autor(a)    : Junior Criste
// @myself.junior    |     @informaticode




Var
// Seção de Declarações das variáveis 
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     
  para contador de 1 ate 10 faca
  escreva(contador)
  fimpara
  
Fimalgoritmo
