Algoritmo "repita...ate"

//  
// Descrição   : Material do Curso de Algoritmos do
//  canal Informaticode: www.informaticode.com.br
// Autor(a)    : Junior Criste
// @myself.junior    |     @informaticode




Var
// Seção de Declarações das variáveis 
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  repita
  escreva (contador)
  contador <- contador + 1
  ate (contador > 10)



     
Fimalgoritmo
