Algoritmo "vetores"
// 
//  

Var
// Seção de Declarações das variáveis 
  numero: vetor[1..5] de inteiro
  i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       numero[1] <- 9
       numero[2] <- 6
       numero[3] <- 2
       numero[4] <- 7
       numero[5] <- 8
       
       para i de 1 ate 5 faca
       escreva(numero[i])
       i <- i + 1
       fimpara
       
Fimalgoritmo