Algoritmo "se...senao"
// se...fimse
// se...senao
// escolha...caso
Var
// Seção de Declarações das variáveis 
  idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreva("Por favor, digite sua idade: ")
  leia(idade)

  se idade >= 18 entao
     escreva("Voce e maior de idade! ")
     senao
     escreva("Voce e menor de idade! ")
     fimse


  
  


Fimalgoritmo