Algoritmo "Contar de Tras Para Frente"


//

// Descrição   : Material do Curso de Algoritmos do

//  canal Informaticode: www.informaticode.com.br

// Autor(a)    : Junior Criste

// @myself.junior    |     @informaticode









Var
// Seção de Declarações das variáveis 
  i: inteiro
Inicio
// Programa para identificar se o numero e par ou impar
  para i de 10 ate 1 passo -1 faca
  escreval(i)
  fimpara


Fimalgoritmo
