Algoritmo "Quadrado"

//

// Descrição   : Material do Curso de Algoritmos do

//  canal Informaticode: www.informaticode.com.br

// Autor(a)    : Junior Criste

// @myself.junior    |     @informaticode





Var
// Seção de Declarações das variáveis 
  num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o numero que deseja saber o quadrado: ")
   leia(num)
   
   escreval("O quadrado e ", num*num)

Fimalgoritmo